version: "3.9"

services:
  telegram-bot:
    ports: 
      - 9898:9898
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

